apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/min-scale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "21"
  source:
    git:
      url: git@github.com:joshlong-attic/tap-ftw.git
      ref:
        branch: main
